import {createSlice} from '@reduxjs/toolkit';

export const OrderSlice = createSlice({
  name: 'cart',
  initialState: {
    all_orders: [
      {
        "order_id": 201680,
        "customer_id": 201570,
        "cart_items_ids": [
          201672
        ],
        "description": "Please deliver quickly.",
        "location_id": 201600,
        "address": "main pwd block A",
        "restaurant_id": "res_4246612",
        "accepted_by_restaurant": false,
        "accepted_by_rider": false,
        "rejectedby": null,
        "rating": 0,
        "rider_id": null,
        "phone_no": "1234567890",
        "promo_code": null,
        "payment_option": "cash",
        "customer_payment": null,
        "comments": "Leave at the door",
        "estimated_delivery_time": 30,
        "order_status": "delivered",
        "total_amount": 2000,
        "created_at": "2024-10-11T02:59:56.141Z",
        "updated_at": "2024-10-11T02:59:56.141Z",
        "delivery_charges": 50,
        "customerData": {
          "customer_id": 201570,
          "user_name": "NewUserName",
          "phone_no": "+1234567890",
          "email": "mahreentassawar@gmail.com",
          "signup_type": "email",
          "password": "$2b$10$0tt5gjizx2xTLrdEFtpGEutk6uaMYOTvRWDTRAjtRT7RI2ZaEIGg6",
          "location": "123 Main St, Springfield",
          "longitude": -77.0364,
          "latitude": 38.8951,
          "fcm_token": "newFCMToken",
          "recieve_notification": true,
          "verified": true,
          "block_status": false,
          "trash": false,
          "created_at": "2024-10-09T00:53:39.553Z",
          "updated_at": "2024-10-09T00:53:39.553Z",
          "recieve_email": true,
          "stripe_customer_id": null
        },
        "cart_items_Data": [
          {
            "cart_item_id": 201672,
            "cart_id": 0,
            "item_id": 201578,
            "item_type": "item",
            "comments": null,
            "quantity": 1,
            "created_at": "2024-10-11T01:50:51.232Z",
            "updated_at": "2024-10-11T01:50:51.232Z",
            "variation_id": 18,
            "itemData": {
              "item_id": 201578,
              "item_name": "new item update",
              "cuisine_id": 201029,
              "description": "item description",
              "price": null,
              "images": [
                "imageurl1",
                "imageurl2"
              ],
              "total_orders": null,
              "restaurant_id": "res_4246612",
              "trash": false,
              "created_at": "2024-10-09T02:51:43.471Z",
              "updated_at": "2024-10-09T02:51:43.471Z"
            },
            "variationData": {
              "variation_id": 18,
              "item_id": 201578,
              "variation_name": "large",
              "price": "2000",
              "created_at": "2024-10-09T02:56:18.516Z",
              "updated_at": "2024-10-09T02:56:18.516Z"
            }
          }
        ],
        "locationData": {
          "location_id": 201600,
          "customer_id": 201570,
          "street_number": "8",
          "area": "pwd",
          "floor": "2",
          "house_number": "14",
          "instructions": "instructions",
          "label": "home",
          "address": "main pwd block A",
          "longitude": -77.0364,
          "latitude": 38.8951,
          "distance": "5 km",
          "trash": false,
          "created_at": "2024-10-10T02:42:22.410Z",
          "updated_at": "2024-10-10T02:48:20.072Z"
        },
        "restaurantData": {
          "restaurant_id": "res_4246612",
          "user_name": "Pizza hut",
          "phone_no": "123456789",
          "email": "ameenullahkhalid1@gmail.com",
          "password": null,
          "fcm_token": null,
          "cnic": "1234567890",
          "buisness_type": "restaurant",
          "buisness_license": "1234567890",
          "buisness_name": "Doe Restaurant",
          "images": [
            "image1.png",
            "image2.png"
          ],
          "location": "New York",
          "rating": null,
          "buisness_address": "123 Main St",
          "buisness_website": "www.doe-restaurant.com",
          "buisness_email": "info@doe-restaurant.com",
          "minimum_order": "10",
          "working_hours": "8 AM - 10 PM",
          "request_status": "verified",
          "recieve_notification": true,
          "recieve_email": true,
          "block_status": false,
          "longitude": 73.080911,
          "latitude": 33.652085,
          "trash": false,
          "created_at": "2023-09-25T05:18:18.727Z",
          "updated_at": "2023-09-25T05:18:18.727Z",
          "restaurant_timing": null,
          "stripe_restaurant_id": "cus_OnBfY6ux94pF9H"
        }
      },
      {
        "order_id": 201682,
        "customer_id": 201570,
        "cart_items_ids": [
          201672
        ],
        "description": "Please deliver quickly.",
        "location_id": 201600,
        "address": "main pwd block A",
        "restaurant_id": "res_4246612",
        "accepted_by_restaurant": false,
        "accepted_by_rider": false,
        "rejectedby": null,
        "rating": 0,
        "rider_id": null,
        "phone_no": "1234567890",
        "promo_code": "promo1",
        "payment_option": "cash",
        "customer_payment": null,
        "comments": "Leave at the door",
        "estimated_delivery_time": 30,
        "order_status": "cancelled",
        "total_amount": 1600,
        "created_at": "2024-10-11T04:35:38.312Z",
        "updated_at": "2024-10-11T04:35:38.312Z",
        "delivery_charges": 50,
        "customerData": {
          "customer_id": 201570,
          "user_name": "NewUserName",
          "phone_no": "+1234567890",
          "email": "mahreentassawar@gmail.com",
          "signup_type": "email",
          "password": "$2b$10$0tt5gjizx2xTLrdEFtpGEutk6uaMYOTvRWDTRAjtRT7RI2ZaEIGg6",
          "location": "123 Main St, Springfield",
          "longitude": -77.0364,
          "latitude": 38.8951,
          "fcm_token": "newFCMToken",
          "recieve_notification": true,
          "verified": true,
          "block_status": false,
          "trash": false,
          "created_at": "2024-10-09T00:53:39.553Z",
          "updated_at": "2024-10-09T00:53:39.553Z",
          "recieve_email": true,
          "stripe_customer_id": null
        },
        "cart_items_Data": [
          {
            "cart_item_id": 201672,
            "cart_id": 0,
            "item_id": 201578,
            "item_type": "item",
            "comments": null,
            "quantity": 1,
            "created_at": "2024-10-11T01:50:51.232Z",
            "updated_at": "2024-10-11T01:50:51.232Z",
            "variation_id": 18,
            "itemData": {
              "item_id": 201578,
              "item_name": "new item update",
              "cuisine_id": 201029,
              "description": "item description",
              "price": null,
              "images": [
                "imageurl1",
                "imageurl2"
              ],
              "total_orders": null,
              "restaurant_id": "res_4246612",
              "trash": false,
              "created_at": "2024-10-09T02:51:43.471Z",
              "updated_at": "2024-10-09T02:51:43.471Z"
            },
            "variationData": {
              "variation_id": 18,
              "item_id": 201578,
              "variation_name": "large",
              "price": "2000",
              "created_at": "2024-10-09T02:56:18.516Z",
              "updated_at": "2024-10-09T02:56:18.516Z"
            }
          }
        ],
        "locationData": {
          "location_id": 201600,
          "customer_id": 201570,
          "street_number": "8",
          "area": "pwd",
          "floor": "2",
          "house_number": "14",
          "instructions": "instructions",
          "label": "home",
          "address": "main pwd block A",
          "longitude": -77.0364,
          "latitude": 38.8951,
          "distance": "5 km",
          "trash": false,
          "created_at": "2024-10-10T02:42:22.410Z",
          "updated_at": "2024-10-10T02:48:20.072Z"
        },
        "restaurantData": {
          "restaurant_id": "res_4246612",
          "user_name": "Pizza hut",
          "phone_no": "123456789",
          "email": "ameenullahkhalid1@gmail.com",
          "password": null,
          "fcm_token": null,
          "cnic": "1234567890",
          "buisness_type": "restaurant",
          "buisness_license": "1234567890",
          "buisness_name": "Doe Restaurant",
          "images": [
            "image1.png",
            "image2.png"
          ],
          "location": "New York",
          "rating": null,
          "buisness_address": "123 Main St",
          "buisness_website": "www.doe-restaurant.com",
          "buisness_email": "info@doe-restaurant.com",
          "minimum_order": "10",
          "working_hours": "8 AM - 10 PM",
          "request_status": "verified",
          "recieve_notification": true,
          "recieve_email": true,
          "block_status": false,
          "longitude": 73.080911,
          "latitude": 33.652085,
          "trash": false,
          "created_at": "2023-09-25T05:18:18.727Z",
          "updated_at": "2023-09-25T05:18:18.727Z",
          "restaurant_timing": null,
          "stripe_restaurant_id": "cus_OnBfY6ux94pF9H"
        }
      },
      {
        "order_id": 201679,
        "customer_id": 201570,
        "cart_items_ids": [
          201672
        ],
        "description": "Please deliver quickly.",
        "location_id": 201600,
        "address": "main pwd block A",
        "restaurant_id": "res_4246612",
        "accepted_by_restaurant": false,
        "accepted_by_rider": false,
        "rejectedby": null,
        "rating": 0,
        "rider_id": null,
        "phone_no": "1234567890",
        "promo_code": null,
        "payment_option": "cash",
        "customer_payment": null,
        "comments": "Leave at the door",
        "estimated_delivery_time": 30,
        "order_status": "pending",
        "total_amount": 0,
        "created_at": "2024-10-11T02:57:16.375Z",
        "updated_at": "2024-10-11T02:57:16.375Z",
        "delivery_charges": 50,
        "customerData": {
          "customer_id": 201570,
          "user_name": "NewUserName",
          "phone_no": "+1234567890",
          "email": "mahreentassawar@gmail.com",
          "signup_type": "email",
          "password": "$2b$10$0tt5gjizx2xTLrdEFtpGEutk6uaMYOTvRWDTRAjtRT7RI2ZaEIGg6",
          "location": "123 Main St, Springfield",
          "longitude": -77.0364,
          "latitude": 38.8951,
          "fcm_token": "newFCMToken",
          "recieve_notification": true,
          "verified": true,
          "block_status": false,
          "trash": false,
          "created_at": "2024-10-09T00:53:39.553Z",
          "updated_at": "2024-10-09T00:53:39.553Z",
          "recieve_email": true,
          "stripe_customer_id": null
        },
        "cart_items_Data": [
          {
            "cart_item_id": 201672,
            "cart_id": 0,
            "item_id": 201578,
            "item_type": "item",
            "comments": null,
            "quantity": 1,
            "created_at": "2024-10-11T01:50:51.232Z",
            "updated_at": "2024-10-11T01:50:51.232Z",
            "variation_id": 18,
            "itemData": {
              "item_id": 201578,
              "item_name": "new item update",
              "cuisine_id": 201029,
              "description": "item description",
              "price": null,
              "images": [
                "imageurl1",
                "imageurl2"
              ],
              "total_orders": null,
              "restaurant_id": "res_4246612",
              "trash": false,
              "created_at": "2024-10-09T02:51:43.471Z",
              "updated_at": "2024-10-09T02:51:43.471Z"
            },
            "variationData": {
              "variation_id": 18,
              "item_id": 201578,
              "variation_name": "large",
              "price": "2000",
              "created_at": "2024-10-09T02:56:18.516Z",
              "updated_at": "2024-10-09T02:56:18.516Z"
            }
          }
        ],
        "locationData": {
          "location_id": 201600,
          "customer_id": 201570,
          "street_number": "8",
          "area": "pwd",
          "floor": "2",
          "house_number": "14",
          "instructions": "instructions",
          "label": "home",
          "address": "main pwd block A",
          "longitude": -77.0364,
          "latitude": 38.8951,
          "distance": "5 km",
          "trash": false,
          "created_at": "2024-10-10T02:42:22.410Z",
          "updated_at": "2024-10-10T02:48:20.072Z"
        },
        "restaurantData": {
          "restaurant_id": "res_4246612",
          "user_name": "Pizza hut",
          "phone_no": "123456789",
          "email": "ameenullahkhalid1@gmail.com",
          "password": null,
          "fcm_token": null,
          "cnic": "1234567890",
          "buisness_type": "restaurant",
          "buisness_license": "1234567890",
          "buisness_name": "Doe Restaurant",
          "images": [
            "image1.png",
            "image2.png"
          ],
          "location": "New York",
          "rating": null,
          "buisness_address": "123 Main St",
          "buisness_website": "www.doe-restaurant.com",
          "buisness_email": "info@doe-restaurant.com",
          "minimum_order": "10",
          "working_hours": "8 AM - 10 PM",
          "request_status": "verified",
          "recieve_notification": true,
          "recieve_email": true,
          "block_status": false,
          "longitude": 73.080911,
          "latitude": 33.652085,
          "trash": false,
          "created_at": "2023-09-25T05:18:18.727Z",
          "updated_at": "2023-09-25T05:18:18.727Z",
          "restaurant_timing": null,
          "stripe_restaurant_id": "cus_OnBfY6ux94pF9H"
        }
      }
    ],
    order_history: [],
  },
  reducers: {
    setAllOrders: (state, action) => {
      state.all_orders = action.payload;
    },
    setOrderHistory: (state, action) => {
      state.order_history = action.payload;
    },
  },
});

export const {setAllOrders, setOrderHistory} = OrderSlice.actions;

export default OrderSlice.reducer;
